esphome:
  name: "esp-indicator"

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-De2B33"
    password: "miX0Wq4MKFNi"

captive_portal:
    
time:
  - platform: homeassistant
    id: homeassistant_time

sensor:
  - platform: homeassistant
    entity_id: sensor.tasmota_sht3x_temperature
    id: pub_temp
    internal: true

  - platform: homeassistant
    entity_id: sensor.tasmota_sht3x_humidity
    id: pub_hum
    internal: true

  - platform: homeassistant
    entity_id: sensor.pircount_pub
    id: pub_pir
    internal: true
    
spi:
  clk_pin: GPIO16
  mosi_pin: GPIO5

display:
  - platform: max7219
    update_interval: 500ms
    cs_pin: GPIO4
    num_chips: 2
    lambda: |-
      
      
      it.printf(12, " %.1f", id(pub_hum).state);
      it.printf(8, " %.1f", id(pub_temp).state);

      static int a = 0;
      a++;
      if ((a % 3) == 0)
        it.print(5, "   ");
      else
        it.printf(5, "%.0f", id(pub_pir).state);
      
      static int i = 0;
      i++;
      if ((i % 2) == 0)
        it.strftime("%H.%M", id(homeassistant_time).now());
      else
        it.strftime("%H%M", id(homeassistant_time).now());



